apiVersion: v1
kind: Service
metadata:
  name: {{.Values.frontend.service.name}}
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{.Values.frontend.service.port}}
      targetPort: {{.Values.frontend.deployment.port}}
  type: ClusterIP
