apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{.Values.frontend.deployment.image}}
          ports:
            - containerPort: {{.Values.frontend.deployment.containerPort}}
