frontend:
  deployment:
    image: romainlancelot/devops-frontend
    imageTag: latest
    port: 80
  httproute:
    hostname: frontend-borg.jbienvenu.fr
  service:
    name: frontend-service
    port: 80
