apiVersion: v1
kind: ConfigMap
metadata:
  name: external-nginx-config
  namespace: borg
data:
  default.conf: |
    server {
        listen 80;
        server_name yourdomain.com;

        location / {
            proxy_pass http://frontend-service.borg:80; # Proxy to the frontend service IN THE BORG NAMESPACE
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
