apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: borg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: romainlancelot/devops-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_BACKEND_API
              value: https://backend-borg.jbienvenu.fr
